### ISSUE TITLE
enhancement: Homekit App status

### ISSUE THREAD

**Issue by oigroigm** [cr3ative/homebridge-apcaccess#1]
Is it possible to add the following information in the Homekit App status?
Battery Level
Charging State
Mains power

Thanks

**Comment by cr3ative** [comment]
Sure, I'm very happy to accept PRs but might get around to this!

**Comment by cr3ative** [comment]
Hi @oigroigm, I had a look at this and I already do report Battery Level and Charging State:

<img width="785" alt="Screenshot 2020-02-25 at 12 18 41" src="https://user-images.githubusercontent.com/1850718/75247058-fdb82180-57c8-11ea-8ac3-2e794be54656.png">

**Comment by cr3ative** [comment]
So - I'm not sure which Homekit characteristic you'd like to see added here. Do let me know!

These values are reported here:

https://github.com/cr3ative/homebridge-apcaccess/blob/master/index.js#L42

**Comment by cr3ative** [comment]
Okay, I had a poke around and I've found that `Service.BatteryService` displays better in Home.app, so I've pushed `0.1.0` which does this:

![IMG_6001](https://user-images.githubusercontent.com/1850718/75247783-a0bd6b00-57ca-11ea-9391-0db0afdaf2cf.PNG)

For "mains power", that's the contact switch; if the switch is open, we're using battery, if it's closed, we're on mains power.

**Comment by cr3ative** [comment]
Fixed!
