### ISSUE TITLE
Suppress Logs

### ISSUE THREAD

**Issue by andrimanna** [cr3ative/homebridge-apcaccess#14]
Would there be the possibility to stop the logs, perhaps by defining a debug and a deploy mode?

**Comment by cr3ative** [comment]
Sure! Why not. Do you know how other plugins do this? I can copy their style. Alternatively, if you want to implement this, I can look at a PR. No promises on speed my side.

**Comment by cr3ative** [comment]
I've published `0.2.1-rc-0`. Can you give it a try and see if it does what you want?

**Comment by andrimanna** [comment]
It works fine, I've tried both with logs on and off and it respects the behavior. Thank you
Unfortunately, i don't have a ups with temperature sensor, thus i can't try that thing.

**Comment by cr3ative** [comment]
Fantastic. I'll publish this in a few days time to give the other person a chance to try their sensor! Thank you!

**Comment by davidjbradshaw** [comment]
You could just do `this.log = log.debug`, however, what would be cool would be to only log the values when they change.

**Comment by cr3ative** [comment]
Resolving - will publish a new version shortly!
